import { GeometryType, NoiseAlgorithm, ShaderParams } from '@/types/shader';

export const GEOMETRY_OPTIONS: { value: GeometryType; label: string }[] = [
  { value: 'sphere', label: 'Sphere' },
  { value: 'box', label: 'Box' },
  { value: 'torus', label: 'Torus' },
  { value: 'plane', label: 'Plane' },
  { value: 'cylinder', label: 'Cylinder' },
  { value: 'cone', label: 'Cone' },
  { value: 'torusKnot', label: 'Torus Knot' },
  { value: 'torusknot', label: 'Torus Knot (legacy alias)' },
  { value: 'icosphere', label: 'Icosphere' },
  { value: 'icosahedron', label: 'Icosahedron (legacy alias)' },
  { value: 'octahedron', label: 'Octahedron' },
  { value: 'dodecahedron', label: 'Dodecahedron' },
  { value: 'tetrahedron', label: 'Tetrahedron' },
  { value: 'capsule', label: 'Capsule' },
  { value: 'disc', label: 'Disc' },
  { value: 'ground', label: 'Ground' },
  { value: 'hemisphere', label: 'Hemisphere' },
  { value: 'knot23', label: 'Knot 2x3 (legacy)' },
  { value: 'knot35', label: 'Knot 3x5 (legacy)' },
  { value: 'trefoil', label: 'Trefoil (legacy)' },
  { value: 'spring', label: 'Spring (legacy)' },
  { value: 'mobius', label: 'Mobius (legacy)' },
  { value: 'klein', label: 'Klein (legacy)' },
  { value: 'heart', label: 'Heart (legacy)' },
  { value: 'gear', label: 'Gear (legacy)' },
];

export const NOISE_OPTIONS: { value: NoiseAlgorithm; label: string }[] = [
  { value: 'perlin', label: 'Perlin' },
  { value: 'simplex', label: 'Simplex' },
  { value: 'worley', label: 'Worley' },
  { value: 'fbm', label: 'FBM' },
  { value: 'voronoi', label: 'Voronoi' },
  { value: 'ridged', label: 'Ridged' },
  { value: 'turbulence', label: 'Turbulence' },
  { value: 'domain_warp', label: 'Domain Warp' },
  { value: 'curl', label: 'Curl' },
  { value: 'gradient', label: 'Gradient' },
  { value: 'value', label: 'Value' },
  { value: 'wavelet', label: 'Wavelet' },
  { value: 'gabor', label: 'Gabor' },
  { value: 'blue', label: 'Blue' },
  { value: 'white', label: 'White' },
  { value: 'plasma', label: 'Plasma (legacy)' },
  { value: 'galaxy', label: 'Galaxy Swirl (legacy)' },
  { value: 'marble', label: 'Marble (legacy)' },
  { value: 'acid', label: 'Acid Wave (legacy)' },
  { value: 'cellular', label: 'Cellular (legacy)' },
  { value: 'warp', label: 'Warped Domain (legacy)' },
  { value: 'truchet', label: 'Truchet Tiles (legacy)' },
  { value: 'mandel', label: 'Mandelbrot-ish (legacy)' },
  { value: 'wave', label: 'Wave Interference (legacy)' },
  { value: 'hex', label: 'Hexagonal (legacy)' },
  { value: 'react', label: 'Reaction Diffusion (legacy)' },
];

export const PARAM_RANGE: Record<string, { min: number; max: number; step: number }> = {
  speed: { min: 0, max: 4, step: 0.01 },
  amplitude: { min: 0, max: 2, step: 0.01 },
  frequency: { min: 0.1, max: 12, step: 0.1 },
  scale: { min: 0.2, max: 4, step: 0.01 },
  rotationSpeed: { min: 0, max: 4, step: 0.01 },
  textureMix: { min: 0, max: 1, step: 0.01 },
  layerBlend1: { min: 0, max: 1, step: 0.01 },
  layerBlend2: { min: 0, max: 1, step: 0.01 },
  layerOpacity1: { min: 0, max: 1, step: 0.01 },
  layerOpacity2: { min: 0, max: 1, step: 0.01 },
  lightIntensity: { min: 0, max: 3, step: 0.01 },
  contrast: { min: 0.5, max: 2, step: 0.01 },
  saturation: { min: 0, max: 2, step: 0.01 },
  gamma: { min: 0.5, max: 3, step: 0.01 },
  glowRadius: { min: 0, max: 2, step: 0.01 },
};

export function formatStatus(params: ShaderParams) {
  return `Geometry: ${params.geometry} | Noise: ${params.noise} | Amp: ${params.amplitude.toFixed(2)}`;
}
